import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Elements",
      items: [
        "elements/what-is-a-brizy-element",
        {
          type: "category",
          label: "Containers",
          items: [
            {
              type: "autogenerated",
              dirName: "elements/containers",
            },
          ],
        },
        "elements/icon",
        "elements/button",
        "elements/image",
        "elements/richtext",
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
  ],
};

export default sidebars;
