import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Elements",
      items: [
        "elements/what-is-a-brizy-element",
        {
          type: "category",
          label: "Containers",
          items: [
            {
              type: "autogenerated",
              dirName: "elements/containers", // Path to the folder relative to the `docs` folder
            },
          ],
        },
        "elements/icon",
        "elements/button",
        "elements/image",
        "elements/richtext",
      ],
    },
  ],
};

export default sidebars;
